services:
  - type: web
    runtime: static
    name: app-storage-owwm
    buildCommand: npm ci && npm run build:web
    staticPublishPath: ./web-build
    envVars:
      - key: EXPO_PUBLIC_API_BASE_URL
        value: https://api-storage-wivi.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
